/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#7598ff",
        "secondary": "#bb0027",
        "tertiary-fixed": "#dbe1ff",
        "secondary-container": "#e0283c",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb3b1",
        "on-error": "#ffffff",
        "surface": "#f9f9ff",
        "outline-variant": "#c4c6d0",
        "inverse-surface": "#273044",
        "secondary-fixed": "#ffdad8",
        "on-secondary-container": "#fffbff",
        "surface-container": "#e9edff",
        "surface-container-highest": "#d9e2fc",
        "on-tertiary-fixed-variant": "#003ea8",
        "primary-fixed": "#d6e3ff",
        "inverse-primary": "#abc7fb",
        "surface-container-high": "#e1e8ff",
        "surface-container-low": "#f1f3ff",
        "outline": "#747780",
        "on-secondary-fixed-variant": "#92001c",
        "primary-fixed-dim": "#abc7fb",
        "surface-dim": "#d1daf4",
        "on-primary-container": "#829dcf",
        "on-tertiary": "#ffffff",
        "surface-tint": "#435f8c",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#2a4773",
        "tertiary": "#001a52",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#43474f",
        "on-error-container": "#93000a",
        "primary-container": "#14345f",
        "tertiary-container": "#002d80",
        "on-tertiary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b4c5ff",
        "surface-variant": "#d9e2fc",
        "on-background": "#121b2e",
        "on-surface": "#121b2e",
        "primary": "#001f43",
        "inverse-on-surface": "#edf0ff",
        "on-secondary-fixed": "#410007",
        "background": "#f9f9ff",
        "on-primary-fixed": "#001b3d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "gutter-lg": "2rem",
        "space-md": "1rem",
        "margin-md": "2rem",
        "space-xs": "0.25rem",
        "margin-lg": "3rem",
        "margin": "1rem",
        "gutter-md": "1.5rem",
        "space-lg": "1.5rem",
        "gutter": "1rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-phone": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-phone": ["20px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "800" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "800" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
